version: "3.9"

services:
    db:
        image: mysql
        container_name: vorspiel_db
        ports:
            - 3306:3306
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: vorspiel

    mailserver:
        image: maildev/maildev
        container_name: vorspiel_mail_server_test
        ports:
            - 1080:1080
            - 1025:1025