version: "3.9"

services:
    db:
        image: mysql
        container_name: vorspiel_db
        ports:
            - 3306:3306
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: vorspiel