server:
    port: 4002
    error: 
        include-message: always


spring:
    ## mysql
    datasource:
        url: jdbc:mysql://localhost:3306/vorspiel
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        open-in-view: false
        
    ## mail (access inbox on localhost:1080)
    mail:
        host: localhost
        port: 1025
        sender: 
            name: Florin Schikarski
            email: florin.schikarski@outlook.de

    config:
        # include .env file
        import: optional:file:.env[.properties]