server:
    port: 4002
    error: 
        include-message: always

## mysql
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/vorspiel
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        open-in-view: false